TechJobs6Persistent/Models/Job.cs
using System;
using Microsoft.Extensions.Logging;

namespace TechJobs6Persistent.Models
{
    public class Job
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Employer Employer { get; set; }
        public int EmployerId { get; set; }

        public ICollection<Skill>? Skills { get; set; }

        public Job(string name)
        {
            Name = name;
            Skills = new List<Skill>();
        }

        public Job()
        {
        }
    }
}

TechJobs6Persistent/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechJobs6Persistent.Data;
using TechJobs6Persistent.Models;
using TechJobs6Persistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobs6Persistent.Controllers
{
    public class EmployerController : Controller
    {
        private readonly JobDbContext _context;

        public EmployerController(JobDbContext context)
        {
            _context = context; 
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            var employers = _context.Employers.ToList();
            return View(employers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var addEmployerViewModel = new AddEmployerViewModel();
            return View(addEmployerViewModel);
        }

        [HttpPost]
        public IActionResult ProcessCreateEmployerForm()
        {
            AddEmployerViewModel addEmployerViewModel = new AddEmployerViewModel
            {
                Name = Request.Form["Name"],
                Location = Request.Form["Location"]
            };

            if (ModelState.IsValid)
            {
                Employer newEmployer = new Employer
                {
                    Name = addEmployerViewModel.Name,
                    Location = addEmployerViewModel.Location
                };
                _context.Employers.Add(newEmployer);
                _context.SaveChanges();
                return Redirect("Index");
            }
            return View("Create", addEmployerViewModel);
        }

        public IActionResult About(int id)
        {
            var employer = _context.Employers.Find(id);
            return View(employer);
        }

    }
}

TechJobs6Persistent/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechJobs6Persistent.Data;
using TechJobs6Persistent.Models;
using TechJobs6Persistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobs6Persistent.Controllers
{
    public class JobController : Controller
    {
        private JobDbContext context;

        public JobController(JobDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Job> jobs = context.Jobs.Include(j => j.Employer).ToList();

            return View(jobs);
        }

        public IActionResult Add()
        {
            List<Employer> employers = context.Employers.ToList();
            AddJobViewModel addJobViewModel = new AddJobViewModel(employers);
            return View(addJobViewModel);
        }
        //Changed from ProcessAddJobForm() to Add()
        [HttpPost]
        public IActionResult Add(AddJobViewModel addJobViewModel)
        {
            if (ModelState.IsValid)
            {
                Employer employer = context.Employers.Find(addJobViewModel.EmployerId);
                Job newJob = new Job
                {
                    Name = addJobViewModel.Name,
                    Employer = employer
                };
                context.Jobs.Add(newJob);
                context.SaveChanges();

                return Redirect("/Job");
            }

             return View(addJobViewModel);

        }

        public IActionResult Delete()
        {
            ViewBag.jobs = context.Jobs.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] jobIds)
        {
            foreach (int jobId in jobIds)
            {
                Job theJob = context.Jobs.Find(jobId);
                context.Jobs.Remove(theJob);
            }

            context.SaveChanges();

            return Redirect("/Job");
        }

        public IActionResult Detail(int id)
        {
            Job theJob = context.Jobs.Include(j => j.Employer).Include(j => j.Skills).Single(j => j.Id == id);

            JobDetailViewModel jobDetailViewModel = new JobDetailViewModel(theJob);

            return View(jobDetailViewModel);

        }
    }
}

TechJobs6Persistent/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechJobs6Persistent.Data;
using TechJobs6Persistent.Models;
using TechJobs6Persistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobs6Persistent.Controllers
{
    public class SkillController : Controller
    {
        private JobDbContext context;

        public SkillController(JobDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Skill> skills = context.Skills.ToList();
            return View(skills);
        }

        [HttpGet]
        public IActionResult Add()
        {
            Skill skill = new Skill();
            return View(skill);
        }

        [HttpPost]
        public IActionResult Add(Skill skill)
        {
            if (ModelState.IsValid)
            {
                context.Skills.Add(skill);
                context.SaveChanges();

                return Redirect("/Skill/");
            }

            return View("Add", skill);
        }

        [HttpGet]
        public IActionResult AddJob(int id)
        {
            Job theJob = context.Jobs.Find(id);
            List<Skill> possibleSkills = context.Skills.ToList();

            AddSkillViewModel addSkillViewModel = new AddSkillViewModel(theJob, possibleSkills);

            return View(addSkillViewModel);
        }

        [HttpPost]
        public IActionResult AddJob(AddSkillViewModel addSkillViewModel)
        {
            if (ModelState.IsValid)
            {
                int jobId = addSkillViewModel.JobId;
                int skillId = addSkillViewModel.SkillId;

                Job theJob = context.Jobs.Include(s => s.Skills).Where(j => j.Id == jobId).First();
                Skill theSkill = context.Skills.Where(s => s.Id == skillId).First();

                theJob.Skills.Add(theSkill);

                context.SaveChanges();

                return Redirect("/Job/Detail/" + jobId);
            }

            return View(addSkillViewModel);
        }

        public IActionResult Detail(int id)
        {
            Skill theSkill = context.Skills.Include(j => j.Jobs).Where(s => s.Id == id).First();

            return View(theSkill);
        }
    }
}

TechJobs6Persistent/Views/Job/Add.cshtml
@model TechJobs6Persistent.ViewModels.AddJobViewModel;

@*This code block declares three variables: employers, name, and employerId.

The first variable, employers, creates a new SelectList object using the Model.Employers property, which is a 
list of employer objects. The "Id" and "Name" strings indicate which properties of the employer objects should be used 
as the value and text for each item in the select list.

The next two variables, name and employerId, use the ViewData.TemplateInfo.GetFullHtmlFieldName method to get the 
full HTML field name for the Name and EmployerId properties of the view model. 
This is necessary because the asp-for attribute in the form later on needs to reference the 
full HTML field name for model binding.*@


<h1>Add Job</h1>

<form asp-controller="Job" asp-action="Add" method="post">
    <div class="form-group">
        <label>Name</label>
        <input class="form-control" asp-for="Name" type="text" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label>Employer</label>
        <select class="form-control" asp-for="EmployerId" asp-items="Model.Employers">
        </select>
        <a asp-controller="Employer" asp-action="Add" class="btn btn-link">Add New Employer</a>
    </div>

    <input type="submit" value="Add Job" />
</form>

@*This code block contains an HTML form for adding a job. The asp-controller and asp-action attributes indicate that the 
form should be submitted to the Add action of the Job controller.
The label elements provide a label for each form field, job name and the employer.

For the job name field, the input element has a class of "form-control" for styling purposes. 
The id and name attributes are set to the name variable defined, and the value attribute is set to @Model.Name, 
which binds the field to the Name property of the view model.

The asp-validation-for attribute is set to @name, which refers to the same name variable as the id and name attributes. 
This attribute is used to display validation error messages if the user enters an invalid value for the job name.

For the employer field, the select element has a class of "form-control" for styling purposes. The id and name attributes 
are set to the employerId variable defined. The asp-items attribute is set to the employers variable defined, 
which populates the select list with the list of employers.*@
  

TechJobs6Persistent/Views/Job/Delete.cshtml
<h1>Delete Job</h1>

<form method="post">
    @foreach (var job in ViewBag.jobs)
    {
        <div class="form-group">
            <label>
                <span>@job.Name</span>
                <input type="checkbox" name="jobIds" value="@job.Id" class="form-control">
            </label>
        </div>
    }

    <input type="submit" value="Delete Selected Jobs" class="btn btn-danger">

</form>

TechJobs6Persistent/Views/Job/Detail.cshtml
@model TechJobs6Persistent.ViewModels.JobDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Employer</th>
        <td>@Model.EmployerName</td>
    </tr>
    <tr>
        <th>Skills</th>
        <td>@Model.SkillText</td>
    </tr>

</table>

<a asp-controller="Skill" asp-action="AddJob" asp-route-id="@Model.JobId">Add more skills to this job</a>

TechJobs6Persistent/Views/Job/Index.cshtml
@using TechJobs6Persistent.Models
@model List<Job>

@{
    ViewData["Title"] = "Tech Jobs Persistent";
}


<div class="text-center">
    <h1 class="display-4">Tech Jobs & Persistent Data</h1>
    @if (Model.Count == 0)
    {
        <p>No jobs yet!</p>
    }
    else
    {
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Employer</th>
            </tr>
            @foreach (var job in Model)
            {
                <tr>
                    <td><a asp-controller="Job" asp-action="Detail" asp-route-id="@job.Id">@job.Name</a></td>
                    <td>@job.Employer.Name</td>
                </tr>
            }
        </table>
    }
    </div>

    <p><a asp-controller="Job" asp-action="Add">Add Job</a></p>

    <p><a asp-controller="Job" asp-action="Delete">Delete Job</a></p>